server:
  port: 8081

spring:
  application:
    name: ms-address
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_address?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true